### ISSUE TITLE
Step 4: Current flow analysis (and some on step 3.2 and 3.4)

### ISSUE THREAD

**Issue by WillPPK** [delemottelab/allosteric-pathways#1]
Hi Annie,

I am trying to run current flow analysis and I came across some problems. 

___________________________________________________________

similarity_map = out_dir+'MI_data/res_res_MI_compressed_'+file_label+'.npy'
similarity_map_diagonal = out_dir+'MI_data/diagonal_MI_'+file_label+'.npy'
contact_maps = [out_dir+'distance_matrix_semi_bin_'+file_label+'.txt']
additional_interactor_protein_contacts = out_dir+'cofactor_protein_residue_semi_binary_cmap_'+file_label+'.npy' 

n_chains=4

source_inds='input_data/inds_sources.txt' 
sink_inds='input_data/inds_sinks.txt'   
aux_inds='input_data/auxiliary_prot_inds.txt' 

compute_current_flow_closeness = False  # False (ie. default) => will compute current flow betweenness. 
                                        # Set this to True to compute current flow closeness centrality between each
                                        # source and all sinks instead.

kwargs={
    'file_label': file_label,
    'out_directory': out_dir,
    'n_chains': n_chains,
    'n_cores': n_cores,
    'similarity_map_diagonal_filename': similarity_map_diagonal,
    'normalize_similarity_map': False,
    'auxiliary_protein_indices': aux_inds,
    'additional_interactor_protein_contacts': additional_interactor_protein_contacts,
    'compute_current_flow_closeness': compute_current_flow_closeness
}

CF = allopath.CurrentFlow(similarity_map, contact_maps, source_inds, sink_inds, **kwargs)
CF.run()

___________________________________________________________

I have been recieving this error when I run the script below on python terminal.
___________________________________________________________

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sansom/s133/trin2642/Open/Small_box/propeller/CG2AT/MD_1/Flow/allosteric-pathways/allopath/current_flow.py", line 118, in run
    self._compute_current_flow_closeness(*self._read_data(contact_map_file))
  File "/sansom/s133/trin2642/Open/Small_box/propeller/CG2AT/MD_1/Flow/allosteric-pathways/allopath/current_flow.py", line 454, in _compute_current_flow_closeness
    self._set_reduced_inverse_Laplacian(sink_nodes)
  File "/sansom/s133/trin2642/Open/Small_box/propeller/CG2AT/MD_1/Flow/allosteric-pathways/allopath/current_flow.py", line 282, in _set_reduced_inverse_Laplacian
    L_red_inv = np.linalg.inv(reduced_L)
  File "<__array_function__ internals>", line 6, in inv
  File "/sansom/s133/trin2642/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 547, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/sansom/s133/trin2642/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
_______________________________________________________

I have supplied inds_sinks.txt as 
168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 
and inds_source.txt as 
7 22 35 36 37 144.
_______________________________________________________
all 4 .npy files are present. The current suspect culprit is 

out_dir+'MI_data/res_res_MI_compressed_'+file_label+'.npy

as the only output those aren't boostrap out of step 3.2 is 

res_res_MI_part_9my_system.npy and not the rest of the res_res_MI_part_[0,8]my_system.npy. All of these are thought to be required to complete part 3.4 of the tutorial. 

So, I made the compressed file by compressing all the res_res_MI_9bootstrap_[0,9]_my_system.npy in step 3.4 and that doesn't seems to work.

If you could help me through this, that would be fantastic!

Best wishes

Will

**Comment by anniewesterlund** [comment]
Hi Will,

Hm, it seems like your reduced Laplacian is singular. 

One thing that I noticed (probably not the issue though) is that you set n_chains=4, which means that you should have a homotetrameric protein with symmetric sources and sinks, but your number of input source_nodes and sink_nodes are not a multiple of 4. The source and sink residues should be given by index (zero-based). So they would correspond to "residue" (ie. not "resid") in a VMD selection. Please do check that the selection is correct with mdtraj (traj.topology.residue(residue_index), in some rare cases there are inconsistencies.

To start debugging your problem, I suggest to first look at the contact map to see if it makes sense.

What additional cofactors are you using?

**Comment by WillPPK** [comment]
Hi Annie,

My additional cofactor is PIP2 so that is pretty standard I think..

Also, what do you mean by the contact map made sense? The cofactor_protein_residue_semi_binary_cmap_my_system.npy 

has dimension of (4, 1316) and the file is not entirely 0 so I think that make sense?

Thank you so much!

Will

**Comment by anniewesterlund** [comment]
Hi Will!
I was thinking that there could be a node that is not connected to the network. One thing you could try is to include the full membrane in the network if e.g. one PIP2 does not interact.

About the MI bootstrapping, I did not understand exactly what the issue was? Did you not get all the output files? Was there an error message?

**Comment by WillPPK** [comment]
Hi Annie,

There is no error message. What's the expected output? Is it 10 bootstrap files (the one with dimension of 329,329 and one additional non-bootstrap file.

What do you mean by the node not connected to the network? You mean the source and the sink are not the lipid binding site? Should I specify the source to be residues at the lipid binding site and the sink to be gating residues?

Will

**Comment by WillPPK** [comment]
Hi Annie,

When you say include a full membrane to the network, do you mean add POPC to the cofactor file?

Also - if I have 4 PIP2. Do I just specify as:

"resname PIP2" in my cofactor_domain_selection.txt or do I need to have 4 lines of:

"resname PIP2 and resid xxx"

and do I need to specify the whole POPC?

Thank you so much!

Best wishes

Will

**Comment by anniewesterlund** [comment]
Hi Will,

By connected, I mean in terms of the network: if the nodes (residues or lipids) are in contact or not.

> When you say include a full membrane to the network, do you mean add POPC to the cofactor file?

Yes, exactly! I had these lines in my cofactor file to specify POPC and PIP2:

```
resname POPC and name N C11 C12 C13 C14 C15 P O13 O14 O12 O11 C1 C2
resname POPC and name O21 C21 C22 O22 C23 C24 C25 C26 C27 C28 C29 C210 C211 C212 C213 C214 C215 C216 C217 C218
resname POPC and name C3 O31 C31 C32 O32 C33 C34 C35 C36 C37 C38 C39 C310 C311 C312 C313 C314 C315 C316
resname SAPI and name N C11 C12 C13 C14 C15 P O13 O14 O12 O11 C1 C2 C16 O6 O5 O4 O3 O2 OP54 OP53 OP52 OP44 OP43 OP42 P5 P4
resname SAPI and name O21 C21 C22 O22 C23 C24 C25 C26 C27 C28 C29 C210 C211 C212 C213 C214 C215 C216 C217 C218 C219 C220
resname SAPI and name C3 O31 C31 C32 O32 C33 C34 C35 C36 C37 C38 C39 C310 C311 C312 C313 C314 C315 C316 C317 C318 
```

So this specifies three nodes per lipid molecule. Hope this helps!

Best,
Annie

**Comment by WillPPK** [comment]
Hi Annie,

It works now! Thank you so much!

Will

**Comment by anniewesterlund** [comment]
Great - I'm happy to hear! :)

Annie
